let progression_list_data = [
    {
        name: "Vanilla",
        credit: "EXOK Games",
        description: "Normal celeste progression.",
        color:"White",
        tags:[],
    },
    {
        name: "Tournament Standard",
        credit: "Maintained by the community",
        description: "You are given one assist skip. Reflection and Summit are both unlocked after Temple. Core is unlocked from the start. Farewell is unlocked after Ridge.",
        color:"White",
        tags:[],
    },
    {
        name: "Banana Split",
        credit: "rhelmot",
        description: "City unlocks Site and Ridge. Either of those unlock Farewell, and also Resort and Temple. Either of those unlock Reflection and Summit. Core is unlocked from the start and beating it counts for one level of progression.",
        color:"Purple",
        tags:[],
    },
    {
        name: "Rocky Road",
        credit: "Aviary",
        description: "Prologue unlocks 1A and Farewell, beating a chapter unlocks adjacent chapters on a following grid.<br><table class='description-table'><tr><td>1A</td><td>2A</td><td>3A</td><td>4A</td><td>5A</td><td>6A</td><td>7A</td><td>8A</td></tr><tr><td>1B</td><td>2B</td><td>3B</td><td>4B</td><td>5B</td><td>6B</td><td>7B</td><td>8B</td></tr><tr><td>1C</td><td>2C</td><td>3C</td><td>4C</td><td>5C</td><td>6C</td><td>7C</td><td>8C</td></tr></table>",
        color:"Blue",
        tags:[],
    },
    {
        name: "Mint Chip",
        credit: "Crab",
        description: "Site unlocks Resort and Ridge. Both of those must be cleared, or one must be cleared and the other skipped, to unlock Temple. Otherwise the same as Tournament Standard.",
        color:"Purple",
        tags:[],
    },
    {
        name: "Cheat Mode",
        credit: "EXOK Games",
        description: "Prologue unlocks all chapters and checkpoints.",
        color:"Blue",
        tags:[],
    },
    {
        name: "Raspberry",
        credit: "notEphim",
        description: "After prologue, you may start any chapter, but this locks all non-played chapters until it is either completed or skipped. Reflection, Core, and Farewell are always unlocked. Site is considered the second half of City, locking out other chapters until both are played in order",
        color:"Blue",
        tags:[],
    },
    {
        name: "Cookies and Cream (v1)",
        credit: "Flyingludicolo",
        description: "After prologue, 6A, 6B & 6C unlock. 6A unlocks 7A & 8A, 6B unlocks 7B & 8B, 6C unlocks 7C, which unlocks 8C, which unlocks 7A, 7B, 8A & 8B. All heart gates are set to require 0 hearts. Beating a checkpoint in 7A unlocks the corresponding A-side (So beating 0M unlocks 1A, 500M 2A, ect.) Beating a checkpoint in 7B unlocks the corresponding B-side (So 0M unlocks 1B, 500M 2B, ect.) (B-sides cas also be unlocked like normal with cassettes.) Beating 7A, 7B, 8A, 8B or 8C unlocks epilogue, beating 8A, 8B or 8C unlocks farewell.",
        color:"Green",
        tags:[],
        external_links:[
            {
                name:"Version of bingo-ui that includes this variant",
                link:"https://discord.com/channels/529677942393929749/689529939975864453/1319461407900831744",
            },
        ],
    },
    {
        name: "Cookies and Cream (v2)",
        credit: "Flyingludicolo",
        description: "After prologue, 6A, 6B, 6C, 7A, 7B, 7C, 8A, 8B & 8C unlock. 8A, 8B & 8C require 4, 5 and 3 hearts respectively. Beating a checkpoint in 7A unlocks the corresponding A-side (So beating 0M unlocks 1A, 500M 2A, ect.) Beating a checkpoint in 7B unlocks the corresponding B-side (So 0M unlocks 1B, 500M 2B, ect.) Completing any B-side unlocks that chapters A-side & C-side. Various checkpoint in farewell can be unlocked through the following ways (unlocking a checkpoint does not give access to earlier checkpoints)<br><table class='description-table'><tr><td>Complete 6B</td><td>Start</td></tr><tr><td>Complete Any 4 Chapters</td><td>Start</td></tr><tr><td>Complete Any 6 Chapters</td><td>Remembered</td></tr><tr><td>Complete 6A</td><td>Stubbornness</td></tr><tr><td>Complete Any 7 Chapters</td><td>Stubbornness</td></tr><tr><td>Complete Any 8 Chapters</td><td>Chapters</td></tr></table>",
        color:"Orange",
        tags:[],
    },
    {
        name: "Raspberry Ripple",
        credit: "PocketWraith",
        description: "Tournament standard (I think idk???) except, when completing an A-side unlocks the next B-side instead of the next A-side. Completing a B-side unlocks the next A-side. Cassettes also unlock B-sides as normal.",
        color:"Orange",
        tags:[],
    },
    {
        name: "Cherry",
        credit: "ilikerandom",
        description: "After prologue, 1A & 7A unlock. Beating a checkpoint in 7A unlocks the corresponding A-side (So beating 0M unlocks 1A, 500M 2A, ect.) Collecting a gem in 7A unlocks the corresponding B-side (So 0M gem unlocks 1B, 500M gem 2B, ect.)(I have 0 clue if tournament standard applies???)",
        color:"Orange",
        tags:[],
    },
    {
        name: "Hokey Pokey",
        credit: "tishk",
        description: "After prologue, 1B unlocks. Completing a B-side unlocks this and the next chapters A-side. (So 1B unlocks 1A & 2A.) Completing an A-side unlocks the next B-side. (So 2A unlocks 3B.) Cassettes function normally. These rules apply for chapters 1-7. Core unlocks after 3 red hearts. Farewell unlocks after 3 Cassettes. Additionally, 5A can also be unlocked by collecting 3 blue hearts, and 6B can be unlocked by completing 5A, 5B, 8A or Remembered (Farewell Checkpoint).",
        color:"Orange",
        tags:["I'm going insane -Cirion"],
    },
    {
        name: "Neapolitan",
        credit: "02c00000",
        description: "After prologue, 1A unlocks. Beating a chapter does nothing, instead A-sides are unlocked as follows. (B-sides are unlocked by cassettes as normal.)<br><table class='description-table'><tr><td>2A</td><td>3 Berries</td></tr><tr><td>3A</td><td>3 Winged berries</td></tr><tr><td>4A</td><td>3 Binoculars</td></tr><tr><td>5A</td><td>3 Blue hearts</td></tr><tr><td>6A</td><td>4 Cassettes</td></tr><tr><td>7A</td><td>4 Keys</td></tr><tr><td>8A</td><td>4 Hearts</td></tr><tr><td>9A</td><td>4 Seeded berries or 4 Red hearts</td></tr></table>",
        color:"Orange",
        tags:[],
    },
]