let variant_list_data = [
    {
        name: "Lockout",
        credit: "Initial draft made by Flesh, updated & maintained by Tim, jacks, marlin, truegen, amber, Spirity, aco, crab, others",
        description: "Two players compete to finish a board of 25 squares. First to tick 13 objectives wins. If one person ticks an objective, the other may not tick it. Prologue cutscenes are not skippable. Standard custom progression rules apply.",
        notes:"The main competitive gamemode and form of Celeste bingo. Highly conducive to strategy.",
        color:"White",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Blackout",
        credit: "Various",
        description: "One or multiple teams of players race to complete a full bingo board of 25 objectives. Prologue cutscenes are not skippable. Standard custom progression rules apply.",
        notes:"The main non-competitive gamemode of Celeste bingo. Less intensive but still reliant on routing. A different generator is used if teams consist of only one player.",
        color:"White",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Ktango (Lockout)",
        credit: "Piano, named 'ktango' by metagloria, popularized by various",
        description: "Two teams of two players play on a bingo board of 25 objectives. Each team has a router, who may see the board, and a player, who cannot see the board but must play the game and get objectives. The router and the player communicate in a voice chat, and the player streams their game footage so the router may tick objectives. The router may not communicate about the board. Standard lockout rules apply.",
        notes:"A ktango-based tournament was held in April 2022. Ktango is sometimes used as a way to teach new bingo routers about the game (Coachtango).",
        color:"White",
        tags:["lockout", "ktango"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2,
    },
    {
        name: "Fog of War",
        credit: "Dragon512, plugin developed by Cirion, Rhuan, ported into Celeste Bingosync by crab",
        description: "A variant of blackout (teams or solo) in which only the lowest-tier objective on the 5x5 board is revealed at the start, and as players tick objectives on the bingo board, adjacent objectives are revealed. Standard blackout rules apply.",
        color:"White",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Masked Bingo",
        credit: "Fladervy, inspired by Age of Empires hidden cup",
        description: "A variant of lockout in which the two players are concealed from each other and any watchers.",
        notes:"A tournament of this style was organized for expert play in March 2021, and for advanced play in June 2021. An option in the BingoUI settings allows for in-game controls to be concealed for this gamemode.",
        color:"Purple",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "New Longo",
        credit: "Adapted from Old Longo by April, metagloria, crab, others",
        description: "A newer, more polished version of longo which fixes typos, removes some difficult objectives, and deletes most multi-chapter variant objectives, to make the game playable.",
        notes:"Almost exclusively played blackout.",
        color:"Purple",
        tags:["blackout", "long", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "3 Line Bingo",
        credit: "Inspired by various other bingo games",
        description: "A variant of solo blackout in which instead of completing the entire board, players are allowed to choose any three lines and complete them. Standard blackout rules apply.",
        notes:"Deceptively difficult to route and strategy-heavy.",
        color:"Purple",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Invasion",
        credit: "buhbai, inspired by Hollow Knight bingo",
        description: "A variant of lockout bingo in which additional rules are imposed to limit what objectives players can tick; see explanatory videos.",
        notes: "Even more reliant on strategy than lockout. Many games are heavily unbalanced from initial ticks. Various generators have been suggested (by Cirion, Piols, and others) for adapting bingo generation to be fair for invasion: none are widely accepted. This can be combined with ktango.",
        color:"Purple",
        external_links:[
            {
                name:"General Explanatory Video",
                link:"https://youtu.be/0HRAjUbGwJo",
            },
            {
                name:"Celeste-Specific Explanatory Video (made by metagloria)",
                link:"https://www.youtube.com/watch?v=OE2887GqBiQ",
            }
        ],
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Lockout (2v2)",
        credit: "Tim",
        description: "A variant of lockout in which each team has two players. One of the two players must complete an objective for their team to tick it. Teammates may communicate.",
        notes:"An event of this style took place during February 2023. It has been suggested that the players on each team are required to alternate ticks.",
        color:"Purple",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2,
    },
    {
        name: "Sinkout",
        credit: "metagloria, Cirion, Dragon",
        description: "A variant of blackout. Two players pick three ships (a 3x1, 2x1, and 2x1 contiguous block of objectives) on their own bingo board. These ships are hidden from the opponent. Players sit in the same VC, and attempt to complete objectives on their opponent's board to discover and sink all three of their opponent's ships. For exach objective completed, the opponent must confirm whether that objective was on a ship.",
        color:"Blue",
        tags:["blackout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Chairgo",
        credit: "metagloria",
        description: "Multiple players play on a bingo board with 25 objectives. While there are n players left, each player must tick at least ceil(10/n) objectives, or ceil(15/n) objectives in cheat mode. Players cannot tick extra objectives, and players may not tick the same objective. The last player to tick their required objectives is eliminated. A new card is generated, and play continues with n-1 players. With 3 players remaining, the game ends and the first, second, and third place finishers are determined in one round.",
        notes:"This gamemode is often played with cheat mode, which reduces round length and decreases reliance on execution. A full game with n people can take about 10*(n-2) minutes.",
        color:"Blue",
        tags:["long"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Zombie Chase Bingo (Zombingo)",
        credit: "metagloria",
        description: "Identical to Chairgo, but players which are eliminated become zombies and also go for objectives.",
        color:"Blue",
        tags:["long"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Ktango (Blackout)",
        credit: "jacks",
        description: "A mixture of ktango and blackout. One router sits in voice call with two players and routes them to complete a board of 25 objectives as fast as possible.",
        color:"Blue",
        tags:["blackout", "ktango"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Kt2ngo",
        credit: "metagloria",
        description: "A variant of ktango in which each team has three people, two routers and one player. Each router routes against an opposing router on a bingo board with 25 objectives, and both routers control the same player to work towards both boards. Routers are not allowed to communicate about their boards or give specific information about their opponent's position. First team to 25 objectives wins.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Kt3ngo",
        credit: "metagloria",
        description: "Identical to Kt2ngo, but the player also has their own board, so three boards are being played concurrently. First team to win two of three boards wins.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Telektango",
        credit: "metagloria, with input from SuperZooper",
        description: "A variant of ktango in which each team has three people: A router, a communicator, and a player. The router is not allowed to look at the player's screen: instead, they must communicate via DMs with the communicator, who can talk to the player and relay information both ways.",
        notes: "Originally known as 'Celeste Bingo 2'. In some games, the router sits in a voice call with the opposing team's communicator and player, to promote communicators to be more vague with their instructors.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Old Longo (Blackout)",
        credit: "April, with input from various others",
        description: "A blackout version of the original longo generator. See Old Longo (Lockout).",
        color:"Blue",
        tags:["blackout", "long", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Row Control",
        credit: "sonicyellow",
        description: "A variant of lockout in which players only need to 'control' three rows to claim victory. Players can control a row by getting any three objectives in that row.",
        color:"Blue",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "3 Line Draft",
        credit: "Unknown, first played by Tiyo, jerky",
        description: "A variant of 3 Line Bingo in which the three lines a player must complete are chosen by the opponent. All 6 chosen lines must be different. Choice goes in the order A, B, B, A, A, B.",
        color:"Blue",
        tags:["blackout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Draft Lockout",
        credit: "notEphim",
        description: "A variant of lockout in which players pick five objectives each that cannot be ticked by the opponent for the first 20 minutes of the match. Chosen objectives must be different. Choice goes in the order A, B, B, A, A, B, B, A, A, B.",
        color:"Blue",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Memoringo",
        credit: "SatelliteSam",
        description: "A variant of lockout in which after 1 minute, all objectives disappear from the board, requiring players to memorize all 25 objectives. A player can try to tick an objective at any point: if that objective is not something they have, they must untick the objective and wait in place for 1 minute.",
        notes:"The ability to make the board disappear is made possible by a plugin developed by SatelliteSam.",
        color:"Blue",
        external_links:[{
            name:"Plugin",
            file:"download-files/memoringo.js",
        }],
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Cirion's Cursed Bingo",
        credit: "Cirion",
        description: "Players play lockout (or blackout) bingo on a completely new generator and board of objectives.",
        notes:"A tournament for this generator (known as Blind Bingo Tournament) was hosted in August 2022. Despite its name, the generator is not incredibly cursed.",
        color:"Blue",
        external_links:[{
            name:"Generator",
            file:"download-files/cirions_cursed_bingo.json",
        }],
        tags:["lockout", "blackout", "difficult", "custom-generator"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Tringo",
        credit: "Xenoras",
        description: "A variant of lockout in which three players attempt to get as many objectives as possible. One player must get a majority of objectives to win: play continues until it is impossible for any player to be overtaken in objective count.",
        notes: "Despite many attempts, a balanced three-player competitive format for bingo has never been found. One variant of Tringo allows 2 players each to tick off an objective.",
        color:"Blue",
        tags:["lockout"],
        min_teams:3,
        max_teams:3,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Variants (Superdash)",
        credit: "None",
        description: "A variant of lockout or blackout in which players play superdash.",
        color:"Blue",
        tags:["lockout", "variants"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Variants (Superdash vs NG+)",
        credit: "None",
        description: "A variant of lockout or blackout in which one player plays superdash and the other plays New Game+ (with 2 dashes).",
        color:"Blue",
        tags:["lockout", "variants"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Rotationally Symmetric Ktango (RSK)",
        credit: "Cookie",
        description: "A truly heinous variant of ktango. There are 4 players: A, B, C, and D. Player A routes Player B. Player B routes player C. Player C routes Player D. Player D routes player A. The two pairs of router/player pairs (A/B with C/D and B/C with D/A) play lockout against each other on the same board. All players sit in the same voice call, with each person but their router muted. The winner is the single player who both wins the game they are routing and wins the game they are playing.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:4,
        max_teams:4,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "6x6 Longo",
        credit: "April",
        description: "A variant of longo meant to be played on a 6x6 board, with even longer objectives.",
        color:"Blue",
        external_links:[{
            name:"Generator",
            file:"download-files/6_by_6_longo.json",
        }],
        tags:["blackout", "long", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Cheat Mode Bingo",
        credit: "metagloria, with input from Reed, crab, Cirion",
        description: "A variant of lockout or blackout in which players begin by activating cheat mode, which lets them access any chapter. A new generator is created to balance accessibility and contain fun things like C-sides.",
        notes: "According to cheat mode rules, 'Complete' a chapter means completing all checkpoints, whereas any collectible (e.g. red hearts) can be obtained just in that checkpoint.",
        color: "Blue",
        tags: ["blackout", "lockout", "custom-generator", "difficult"],
        min_teams: 1,
        max_teams: null,
        min_players_per_team: 1,
        max_players_per_team: null,
    },
    {
        name: "Twitch Plays Ktango (TPK)",
        credit: "crab",
        description: "Requires exactly 6 people. One person is designated the 'player', while the other 5 are 'routers', each having a bingo board. The first router to complete 3 lines on their bingo board wins. All routers anonymously post instructions for the player in the same channel, 'Twitch Chat', and the player follows the most recently posted instruction, unless it is vetoed by a majority of players.",
        external_links:[{
            name:"Detailed Ruleset",
            link:"https://discord.com/channels/529677942393929749/1125096018317418627/1125215297364819988",
        }],
        color:"Blue",
        tags: ["ktango", "blackout"],
        min_teams: 6,
        max_teams: 6,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Predictiongo",
        credit: "ilikerandom",
        description: "Two players are given a board of 25 objectives and they must each make a list of times they expect the objectives to be ticked. A separate player plays the entire board blackout, and whoever's guessed time for that objective is closest to when it is actually completed gets the objective. Whoever gets a majority of objectives wins.",
        color: "Blue",
        tags: ["cursed"],
        min_teams: 3,
        max_teams: 3,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "4x4 Bingo",
        credit: "talia",
        description: "Two players are given a board of 25 objectives. One player chooses a row or column to delete from the board, then the other player chooses a column or row to delete from the board. Players play lockout on the 16 remaining objectives.",
        notes: "It has been suggested that the objective in both the selected row and column could also be allowed to be played, so that there are 17 objectives and ties are no longer possible.",
        color:"Blue",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "VC Lockout",
        credit: "none",
        description: "A variant of lockout in which players sit in the same VC, allowing for players to lie to each other and use social cues to try guess where the other player is.",
        color:"Blue",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Rocky Road",
        credit: "Reed, Generator by rhelmot",
        description: "A variant of lockout (or blackout) in which players play a game of lockout with Rocky Road Progression.",
        color:"Blue",
        tags: ["lockout", "custom-generator"],
        external_links: [{
            name: "Generator",
            file: "download-files/Lockout_RockyRoad.json"
        }],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1
    },
    {
        name: "k単語",
        credit: "Random Name",
        description: "A variant of ktango in which routers communicate with their players in a foreign language.",
        color:"Green",
        tags: ["lockout", "ktango", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 2,
        max_players_per_team: 2
    },
    {
        name: "2 experts, 1 beginner (2x1b)",
        credit: "Lmjacks, with input from various",
        description: "A variant of blackout in which a team of 2 experts play against a beginner without losing a single objective.",
        notes: "This variant must be played on Banana Split progression and must not contain pico objectives longer than \"Reach Old Site in PICO-8\" to remove early skip advantage and PICO-8 rushes. A variation of 2x1b has 2 experts play against any opponent where the number of objectives needed to win is agreed upon prior to the match.",
        color:"Green",
        tags: ["lockout", "blackout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 2
    },
    {
        name: "Symmetrical Ktango",
        credit: "notEphim",
        description: "A variant of ktango in which teams of players route each other to have their partner complete objectives on a board that only they can see. Can be played lockout, blackout, or 3 line.",
        color: "Green",
        tags: ["lockout", "blackout", "ktango", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 2,
    },
    {
        name: "Reverse Kt3ngo",
        credit: "Unknown",
        description: "Identical to Kt3ngo, but instead of each team having 2 routers and 1 player, each team has 1 router and 2 players, and the routers can tick anything that either of their players do. First team to win two of three boards wins.",
        color: "Green",
        tags: ["lockout", "ktango", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 3,
        max_players_per_team: 3,
    },
    {
        name: "Ktango Taboo",
        credit: "metagloria",
        description: "A more strict version of ktango in which routers cannot say any of the words on the bingo board, but must allude to objectives to route the player.",
        color: "Green",
        tags: ["lockout", "ktango"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 2,
        max_players_per_team: 2,
    },
    {
        name: "3 Board Lockout",
        credit: "April, roofon",
        description: "A variant of lockout in which the players play three boards at once, and the first to complete two boards wins.",
        color: "Green",
        tags: ["lockout", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Follow the Leadergo",
        credit: "metagloria",
        description: "Multiple players (more than 2) play on a bingo board with 25 objectives. One person is designated the 'leader' and declares an objective that all players must go for. The leader may not tick that objective. The first person to tick the declared objective becomes the new leader, and declares another objective which everyone must go for. Play continues until all 25 objectives are declared and ticked.",
        color: "Green",
        tags: ["blackout"],
        min_teams: 1,
        max_teams: null,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Variants (100x Dash Speed)",
        credit: "Cirion",
        description: "A variant of lockout in which players play with 100x dash speed.",
        notes: "Setting dash speed to 100x requires use of the Extended Variants mod. A custom generator is used to remove many impossible objectives.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/100x_dash_speed.json",
        }],
        tags: ["lockout", "variants", "custom-generator", "difficult"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Variants (0 Gravity)",
        credit: "Cirion, Generator by Random Name",
        description: "A variant of lockout in which players play with 0 gravity.",
        notes: "Setting 0 gravity requires use of the Extended Variants mod. A custom generator is used to remove many impossible objectives.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/0_gravity.json",
        }],
        tags: ["lockout", "variants", "custom-generator", "difficult"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Reed's Cursed Bingo",
        credit: "Reed",
        description: "Players play lockout (or blackout) bingo on a completely new cursed generator and board of objectives.",
        notes: "Unbalanced.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/reeds_cursed_bingo.json",
        }],
        tags: ["lockout", "custom-generator", "difficult", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Individual Berry Bingo",
        credit: "metagloria",
        description: "Players play lockout bingo on a custom generator, each objective of which contains only a single collectible (berry, binos, PICO-8 berry, or heart).",
        notes: "Unbalanced. Use the Randomized setting to create a board, not the srlv5 setting.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/individual_berry_bingo.json",
        }],
        tags: ["lockout", "custom-generator"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "4-In-A-Row",
        credit: "metagloria, Reed",
        description: "A variant of lockout in which players need to tick any four objectives in a row to claim victory. If it is impossible for either player to win, the game ends in a draw.",
        notes: "Wraparounds may or may not be allowed.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Postage Stamp Bingo",
        credit: "metagloria, Reed",
        description: "A variant of lockout in which players need to tick any four objectives in a square to claim victory. If it is impossible for either player to win, the game ends in a draw.",
        notes: "Wraparounds may or may not be allowed.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "B3ngo",
        credit: "metagloria",
        description: "A variant of lockout in which three players play. Three boards are generated, and each player plays on two boards at the same time, forming a cycle. Play continues until all objectives are ticked, and whoever has the most objectives in total wins.",
        color: "Green",
        tags: ["lockout", "cursed"],
        min_teams: 3,
        max_teams: 3,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Spring Collab Bingo (Springo)",
        credit: "hydrei, metagloria",
        description: "A variant of lockout bingo played on the 2020 Spring Collab mod.",
        notes: "A generator was never finished, but many objectives for the Beginner section were made.",
        color: "Green",
        external_links:[{
            name:"Generator Scraps",
            link:"https://docs.google.com/spreadsheets/d/16YVIat4UIjuy_TvXCU9RX03_3fGmi5et0qN_ElduQik/edit#gid=497655973",
        }],
        tags: ["lockout", "custom-generator", "unplayable"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Old Longo (Lockout)",
        credit: "April, metagloria, with input from various others",
        description: "A variant of lockout bingo with objectives that are longer than usual, including objectives from multiple B-sides, in-game variants, and Chapter 9.",
        notes: "Originally created as a joke, old longo eventually grew in popularity and was updated to new longo. In general, it is inadvised to play the original old longo without practice, as some objectives are extremely difficult and/or variant-heavy.",
        color: "Green",
        tags: ["lockout", "custom-generator", "difficult", "long"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Crow Control Bingo",
        credit: "Azula, wiz independently",
        description: "An application of the 'Crow Control' Celeste mod to bingo. Two players play bingo while both games are hooked up to a single twitch stream, in which viewers may spawn obstacles or cause the players to gain variants, die, or become invincible.",
        color: "Green",
        tags: ["lockout", "long"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Old Lockout",
        credit: "None",
        description: "A variant of lockout in which players play on the old lockout generator from before chapter 9 was released. Players do not play with custom progression. Prologue cutscenes are unskippable.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/old_lockout.json",
        }],
        tags: ["lockout", "long", "unplayable"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Line Lockout",
        credit: "Random Name",
        description: "A variant of lockout in which one player attempts to get a single line (5 objectives in a row) and the other player tries to stop them.",
        notes: "Favors the player attempting to block the line.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "25 Objective Draft",
        credit: "metagloria",
        description: "A variant of lockout in which players begin by picking all objectives on the board from the generator of 200+ objectives. Players alternate picking objectives from each of the generator's 25 tiers: once an objective from a tier has been chosen, no other objective from that tier can be chosen. Once all 25 objectives are chosen, normal lockout play begins.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Adjacent Pair Bingo",
        credit: "metagloria",
        description: "A variant of lockout bingo in which players must tick pairs of adjacent objectives simultaneously. If there are no remaining such pairs, any objectives may be ticked. First to 13 wins.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Bingo but Canon",
        credit: "Reed",
        description: "A variant of lockout bingo in which each player has a 'life' counter starting at 1. Collecting a 1-UP increases a player's life counter by 1. Dying reduces a player's life counter by 1. If a player's life counter drops to 0, they must delete their file and start a new file, replaying prologue.",
        color: "Green",
        tags: ["lockout", "cursed", "difficult"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Farewell Bingo",
        credit: "Cookie",
        description: "A variant of lockout in which all the objectives are in Farewell.",
        color: "Green",
        external_links:[{
            name:"Generator + Additional Ruleset",
            link:"https://docs.google.com/document/d/1_saXKc-ucMCS7203HLUcBEr70KLff6xkXeY_WLMCIOg/edit",
        }],
        tags: ["lockout", "short", "custom-generator"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Bingo???",
        credit: "Reed, ad",
        description: "A variant of lockout bingo in which objectives are taken literally and can be completed in non-traditional ways. In addition, cheating is allowed and frequently encouraged. For example, a square reading \"Reflection A-Side\" may be completed by playing any A-Side mirrored, or players may tick \"Golden Ridge B-Side\" when actually in Resort.",
        color: "Green",
        tags: ["lockout", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Bingobuthardtoread",
        credit: "Random Name",
        description: "A variant of lockout bingo in which objectives in the standard generator are replaced with objectives which require doing the exact same thing, but are significantly harder to understand or parse. As an example, \"10 Berries in 3 Chapters\" could be replaced with \"As many berries as exist in 2A Start, collected in a number of different chapters equal to the number of chapters containing snowballs\".",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/bingobuthardtoread.json",
        }],
        tags: ["lockout", "custom-generator", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Minesweeper Bingo",
        credit: "Cirion, previously suggested by gnommis, metagloria, crab, oolimry, independently",
        description: "A variant of blackout bingo in which some unknown objectives are marked mines, and ticked objectives reveal the number of adjacent mines. The goal is to tick all non-mine objectives. Objectives much be ticked when obtained. Ticking an objective with a mine instantly loses, unless that mine objective is required to complete a different non-mine objective.",
        notes: "It is suggested to play on a 7x7 board with 13+ mines.",
        color:"Green",
        external_links:[{
            name:"Bookmark",
            file:"download-files/bingoMinesweeper.js",
        }],
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Bingo with Anti-Delaying",
        credit: "Linus",
        description: "A variant of lockout bingo in which a player may anti-delay objectives by ticking them off before getting them. If the opponent calls their bluff by completing an anti-delayed objective, the bluffer loses the game immediately. If the bluffer safely completes a bluffed objective, that objective can no longer be stolen. First to 13 real objectives wins.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Invasion Racing",
        credit: "Unknown",
        description: "Two or four players start on opposing sides of the board. Each player must get an objective on the opposite side of the board from where they started, via invasion-like rules for building forward. If an objective is ticked off, no other player may tick it. Players may only tick one objective on each of the 5 rows (or columns) that they need to win.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:4,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Half-Fog Lockout",
        credit: "jacks",
        description: "A variant of lockout bingo with two players, one with better execution. The player with better execution plays using Fog of War spectator mode, where only the first two tiers of objectives are revealed at the start and ticking something reveals all adjacent squares. The player with worse execution sees the whole board to begin with.",
        notes: "There is currently no automatic way to reveal two starting objectives in the fog of war mode on Celeste Bingosync.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Bingobutslightlylonger",
        credit: "Epyc",
        description: "A variant of lockout bingo with slightly longer objectives.",
        color:"Green",
        external_links:[{
            name:"Generator",
            file:"download-files/bingobutslightlylonger.json",
        }],
        tags:["lockout", "custom-generator", "long"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "One Way Lockout",
        credit: "Random Name",
        description: "An unbalanced variant of lockout bingo in which Player A cannot tick objectives that player B has, but Player B can. Whoever has more objectives when all 25 squares are ticked wins.",
        notes:"This directly favors Player B, making it ideal when players have a skill deficit.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Chessgo",
        credit: "Cirion",
        description: "64 bingo objectives are placed on a chessboard. Normal chess pieces are also placed on the chess board. By completing an objective on a square, you may move a piece to that square (if that movement is valid by chess rules), and the objective on it gets refreshed. There is no turn order. Whoever captures the opponent's king first wins.",
        color:"Green",
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Asyncgo",
        credit: "rhelmot",
        description: "A variant of lockout bingo in which two people play all 25 objectives on a bingo board, and then ticks and lockouts are applied retroactively, so that players must route without knowing what their opponent's route is. After both players have ticked all objectives, logs are examined to decide who won what objective. Whoever wins 13 or more objectives wins.",
        notes:"This can be played with one opponent being a TAS, and is referred to as TAS Blackout.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Table Turf Bingo",
        credit: "FlyingLudicolo",
        description: "A variant of lockout bingo. Each team starts with an objective ticked on symmetrical sides of the board. Players may only tick objectives that are adjacent to an objective they already have (or diagonally if that objective is blocked off on all 4 sides). Most objectives ticked in a predetermined time limit win. One way to start the match is on a 10x5 board, where team 1 starts with r3c2 and team 2 starts with r3c9. When matches are played on a 7x7 board, team 1 starts with r5c2 and team 2 starts with r3c6.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Untieredgo",
        credit: "Epyc, Random Name",
        description: "A variant of bingo where objectives are untiered, allowed for ridiculous amounts of synergy, multiple tier 25 objectives, or other silly stuff.",
        notes: "Due to the way probability works, most boards are nondescript and indeed indistinguishable from a normal lockout board. To play this, use the Randomized option on Celeste Bingosync.",
        color:"Green",
        external_links:[{
            name:"Generator",
            file:"download-files/untieredgo.json",
        }],
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Bingolf (Antibingo)",
        credit: "Cirion",
        description: "A variant of Any% in which a board of 25 bingo objectives containing things people do in Any% is revealed, and players must complete an Any% run without doing as few of these objectives as possible.",
        notes: "This has supposedly been played, but I have no clue where the generator is.",
        color:"Green",
        tags:["lockout", "custom-generator", "unplayable"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Infectiongo",
        credit: "bulletinfi",
        description: "A variant of lockout in which two players attempt to tick all 25 objectives. When an objective is ticked, all directly adjacent objectives belonging to the opponent are turned the color of that tick. Once all 25 objectives are ticked, the person with 13 or more objectives wins.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Renegadego",
        credit: "Dragon",
        description: "A variant of lockout bingo in which getting 2 objectives next to a square automatically wins you that square.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Community Generator",
        credit: "Cookie, with objectives suggested by about 20 different people",
        description: "A variant of lockout (or blackout) bingo in which players play with an entirely new set of objectives, created by the community.",
        notes: "Created more as a social experiment than an actual bingo variant. Use the Randomized setting to generate the board.",
        color:"Green",
        external_links:[{
            name:"Generator",
            file:"download-files/community_generator.json",
        }],
        tags:["lockout", "blackout", "custom-generator"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Celeste Bingo Challenge",
        credit: "Random Name, Cookie",
        description: "A variant of lockout (or blackout) bingo in which players play with a list of obejctives that consists of short challenges. Cheat mode and debug mode are allowed, and savestates may be used for practice. Pause buffering is banned.",
        notes: "Use the Randomized setting to generate the board.",
        color:"Green",
        external_links:[{
            name:"Generator",
            file:"download-files/celeste_bingo_challenge.json",
        }],
        tags:["lockout", "blackout", "custom-generator", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Positive Negative Bingo",
        credit: "bulletinfi",
        description: "A variant of lockout in which players have 2 standard lockout boards. The first is played normally, but on the second board, players must tick off objectives immediately if completed. Objectives on the second board reduce a player's score by 1. Whoever has more points when the first board is completed wins.",
        color:"Green",
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Minibingo (Blitzgo)",
        credit: "metagloria",
        description: "A variant of lockout in which players play on the central 3x3 miniature board. Only these 9 objectives may be ticked. First to 5 objectives wins.",
        notes: "Often played when players do not have enough time for a complete bingo match. Highly imbalanced.",
        color:"Green",
        tags:["lockout", "short"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Strikego",
        credit: "Cirion",
        description: "A variant of lockout bingo in which when a player gets an objective, they may pick another objective to delete from the game. First to 7 wins.",
        color:"Green",
        tags:["lockout", "short"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Othellgo or Bingothello",
        credit: "metagloria, Ninja independently",
        description: "A variant of lockout in which whenever a player ticks an objective, such that there is in one of the 8 cardinal directions only objectives belonging to the opponent, followed by an objective of the ticking player, then all objectives in between the player's two objectives are turned the player's color.",
        color:"Green",
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Clockwork",
        credit: "Strawberry",
        description: "A variant of lockout in which after ticking an objective, a player cannot tick another objective for 2 more minutes.",
        notes: "A contender for the worst bingo variant. Don't try.",
        color:"Green",
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Pyramidgo",
        credit: "ilikerandom",
        description: "A variant of blackout bingo in which before the game players pick a row and a column in which 5 objectives must be done, a row and a column in which 4 objectives must be done, and so on, until picking a row and a column where 1 objective must be done. Then, players play standard blackout, only completing the required objectives.",
        color:"Green",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null
    },
    {
        name: "VIPgo",
        credit: "ilikerandom",
        description: "A variant of lockout in which each player, before the game, selects one special \"VIP\" objective. Players do not know their opponent's VIP objective. If a player manages to successfully tick off their opponent's VIP objective, they immediately win.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Oldsitego",
        credit: "ad",
        description: "A variant of lockout (or blackout) in which all the objectives are Old Site related",
        color: "Green",
        external_links: [{
            name:"Generator",
            file:"download-files/oldsitego.json"
        }],
        tags:["lockout", "blackout", "custom-generator", "cursed"],
        min_teams:1,
        max_teams: null,
        min_players_per_team:1,
        max_players_per_team:null
    },
    {
        name: "Artgo",
        credit: "bulletinfi, Epyc independently",
        description: "On a large bingo board, players complete objectives to make pixel art.",
        color:"Green",
        tags:["blackout"],
        min_teams:1,
        max_teams:1,
        min_players_per_team:1,
        max_players_per_team:null
    },
    {
        name: "Celestenet Bingo",
        credit: "April",
        description: "A variant of lockout bingo in which players are in celestenet. Player interactions may or may not be enabled. No clear ruleset has been formalized.",
        color:"Orange",
        tags:["lockout", "unplayable"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Relay Bingo",
        credit: "talia",
        description: "A variant of lockout bingo in which each team has 4 people. One person from each team begins the bingo game, and after some amount of time, the two players stop the game and transfer their respective save files to a teammate, who then continues the game. Swapping continues until one team has 13 objectives.",
        notes:"Metagloria and Morraconda suggested an alteration where each team has a beginner, intermediate, advanced, and expert player, and the teams are allowed to choose to put their players in any order. The first player plays for 5 minutes, then the next player for 10, then the next for 15, then the last continues until one team has 13. Thus, teams can strategize whether they want to put their fastest players early or late.",
        color:"Orange",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:4,
        max_players_per_team:4,
    },
    {
        name: "Ktango with Code",
        credit: "Cookie",
        description: "A variant of ktango in which all communication between players and routers is made public to both teams, so that routers must attempt to give instructions to players without giving information to the opposing router (e.g. via a secret code).",
        color:"Orange",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2,
    },
    {
        name: "Limericktango",
        credit: "metagloria",
        description: "A more strict version of ktango in which routers must speak in limerick.",
        color:"Orange",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2,
    },
    {
        name: "Bullsh*t Bingo",
        credit: "MathHacker",
        description: "A variant of lockout bingo in which a player may tick objectives off before getting them. The opponent may challenge any tick that is made, at any time. If the tick was fake at the time of making the tick, the player who made the bluff must sit still for 30 seconds and the opponent gets the objective (without needing to complete it). If the tick was real, play continues. Players may only fail 3 challenges: if 3 challenges are failed, a player may no longer challenge objectives.",
        color:"Orange",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Prologue-Based Bingo",
        credit: "FlyingLudicolo",
        description: "Two players play on a non-lockout board of 25 objectives. When a player ticks an unclaimed objective, they are unable to tick any more objectives until their opponent ticks an unclaimed objective or they replay Prologue. First to 17 wins.",
        color:"Orange",
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Microbingo",
        credit: "Dragon",
        description: "A variant of lockout in which players play cheat mode, but the objectives are extremely quick, taking just seconds to do. No such generator currently exists.",
        notes: "Has been suggested as a TAS challenge.",
        color:"Orange",
        tags:["lockout", "short", "custom-generator", "unplayable"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Dr. Mario Bingo",
        credit: "metagloria",
        description: "Each player gets a line of 5 objectives. Completing an objective adds another objective to one's opponent, and vice versa. Whoever finishes all of their objectives first wins.",
        color:"Green",
        tags:[],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Among Us Bingo",
        credit: "metagloria",
        description: "Many players (4 or more) are put in a bingosync room. One player is designated to be the impostor. All other players are given a list of objectives to complete. The impostor must kill crewmates by completing objectives that the crewmates were supposed to do. The crewmates must vote out the impostor.",
        color:"Orange",
        external_links:[{
            name:"Detailed Ruleset",
            link:"https://discord.com/channels/529677942393929749/689529939975864453/1023348808836464681",
        }],
        tags:["cursed", "unplayable"],
        min_teams:4,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Wordle Bingo",
        credit: "Reed",
        description: "A combination of Wordle and bingo for two-player competitive play.",
        color:"Orange",
        external_links:[{
            name:"Detailed Ruleset",
            link:"https://discord.com/channels/529677942393929749/689529939975864453/1023348808836464681",
        }],
        tags:["cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Ktanego",
        credit: "Cirion",
        description: "A combination of KTANE (Keep Talking and Nobody Explodes) with bingo, including things like modules.",
        color:"Orange",
        notes:"Currently still a work in progress by Cirion.",
        tags:["blackout", "unplayable"],
        min_teams:1,
        max_teams:1,
        min_players_per_team:2,
        max_players_per_team:2
    },
    {
        name: "Tic-Tac-go",
        credit: "Random Name",
        description: "Two players play on a 3x3 board of 9 mess orders, including 4-length orders like Chests-Books-Towels-Books. If a player completes a line of 3 orders, they win.",
        color:"Green",
        external_links:[{
            name:"Generator",
            file:"download-files/tic_tac_go.json",
        }],
        tags:["lockout", "short", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Codenames Bingo",
        credit: "Cirion",
        description: "A variant of lockout bingo inspired by the game Codenames. Divide the board randomly into 3 groups: red, blue and neutral, with 9, 9, and 7 objectives respectively. There are two teams of two people. Each team has a player, who plays the game and ticks objectives and an informer, who gets to know the objectives of their color. All people are in the same call. The goal of the game is to tick the majority of the 18 non-neutral objectives (including the opponents').",
        color:"Orange",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2
    },
    {
        name: "Desyncgo",
        credit: "metagloria",
        description: "A variant of lockout bingo in which each player has their own board. A third, neutral player (the relayer) enters both rooms. Each time an objective is ticked on one board, the relayer ticks the objective that is in the same position on the other team's board. First to 13 wins.",
        notes: "Has been suggested in a ktango format, desynktango.",
        color:"Orange",
        tags:["lockout", "ktango", "cursed"],
        min_teams:3,
        max_teams:3,
        min_players_per_team:1,
        max_players_per_team:2
    },
    {
        name: "Bingoku",
        credit: "Reed",
        description: "81 bingo objectives are put on a 9x9 board. Completing an objective reveals a number. The grid forms a valid sudoku. Finish the sudoku (which may not require completing all objectives) to win.",
        color:"Orange",
        tags:["blackout", "long", "cursed"],
        min_teams:1,
        max_teams:1,
        min_players_per_team:1,
        max_players_per_team:null
    },
    {
        name: "Passgo",
        credit: "Poynting",
        description: "A combination of monopoly and bingo. Has no formalized ruleset.",
        color:"Orange",
        tags:["unplayable"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Masochistgo",
        credit: "Cirion",
        description: "A variant of lockout bingo in which all objectives are extremely difficult challenges.",
        color:"Orange",
        external_links:[{
            name:"Generator Mockup",
            link:"https://discord.com/channels/529677942393929749/689529939975864453/1110977512642719804",
        }],
        tags:["lockout", "difficult", "cursed", "unplayable", "custom-generator"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Trackmania Bingo",
        credit: "Cirion, Generator by creep.",
        description: "A bingo board with 25 ILs (or checkpoints) on it is created. 2 teams fight to get one or two complete lines on the board. To tick off a square for the first time, a player must beat that IL, and note their time for completing it. Any player on either team can then steal that square by completing the IL in a faster time, also lowering the time needed to steal that square again.",
        notes: "Use the Randomized setting to create a board, not the srlv5 setting. There is no way of keeping track of IL times without recording the time externally.",
        color:"Orange",
        external_links: [{
            name:"Generator + Additional Ruleset",
            link:"https://docs.google.com/spreadsheets/d/1y8Pxg9ARSgLRuE25jj2yRWSSveKdVk4mATQf0MPkbBw/edit?usp=sharing"
        }],
        tags:["custom-generator"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:null
    },
    {
        name: "Blindfolded Ktango",
        credit: "Dragon, Cookie",
        description: "A variant of ktango in which the player on each team must be blindfolded and guided through the game by the router. As the game would last for much longer than a usual bingo game would, a shorter bingo generator was made that uses Cheat Mode.",
        notes: "Use the Randomized setting to generate the board",
        color:"Orange",
        external_links:[{
            name:"Generator",
            file:"download-files/blindfolded_ktango.json",
        }],
        tags:["lockout", "ktango", "custom-generator", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2
    },
    {
        name: "Splatoongo / Thiefgo",
        credit: "idontexist, ilikerandom independently",
        description: "A board is generated with 25 very short, nonspecific, repeatable objectives (such as 'Get 1 bino' or 'Get to a multiple of 5 berries'). If you complete an objective, you may tick it your color, and your progress to that objective resets. You may override another player's ticked cell, if you have just completed the objective. After a fixed period of time, the player with more completed objectives wins.",
        notes: "No generator currently exists. ilikerandom suggested Thiefgo, a similar variant but using the original generator, with delaying disallowed, and only allowing players to steal an objective a finite number of times.",
        color:"Orange",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Lönngo",
        credit: "MathHacker",
        description: "A variant of lockout bingo in which players can edit the maps in Lönn as they play.",
        color:"Orange",
        tags:["lockout", "unplayable"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Longergo",
        credit: "Cirion",
        description: "An even longer version of longo, with objectives that are only theoretically possible to complete.",
        color:"Red",
        external_links:[{
            name:"Objective List",
            file:"download-files/longergo.png",
        }],
        tags:["lockout", "long", "difficult", "cursed", "unplayable", "custom-generator"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Celeste Bingo 2 (Metabingo)",
        credit: "FlyingLudicolo",
        description: "A variant of lockout bingo in which every square itself is an entire bingo board subject to some additional constraint, such as 'super dashing on' or 'assist skip city'. Winning a bingo board with that constraint gets a player one mini-board. First to 13 objectives on each mini-board wins that mini-board. First to 13 mini-boards wins.",
        notes: "JimmyClyde suggested having each square be a separate bingo variant. Metagloria suggested having an entire bingo tournament where every round or game is a new variant. A tournament for this format was started in September 2023, but it was unfinished due to general player disinterest.",
        color:"Red",
        tags:["lockout", "long", "unplayable"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:null
    },
    {
        name: "K3-by-2ngo",
        credit: "Random Name",
        description: "A variant of symmetric ktango. There are 2 teams of 3 players. Each player on each team routes each other player on their team. So there are 6 games of bingo being played simultaneously. The first team to 75 objectives wins.",
        notes: "Due to the immense skill required to route two bingo boards, communicate with two people, and execute one's own bingo board, all while ticking objectives, and due to the fact that all 6 players must be willing to do so, it is the opinion of this author that while this variant is not physically unplayable, it is practically unplayable.",
        color:"Red",
        tags:["lockout", "unplayable", "cursed", "difficult"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3
    },
    {
        name: "Fullgo",
        credit: "Epyc",
        description: "A variant of lockout bingo in which every square requires you to complete an extremely long objective from an entirely new save file. After completing and ticking an objective, that save file must be deleted.",
        color:"Red",
        external_links:[{
            name:"Objective List",
            file:"download-files/fullgo.json",
        }],
        tags:["lockout", "unplayable", "long", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Musical Squares",
        credit: "BlueMushroom",
        description: "26 players are given a board of 25 objectives. The last to complete an objective is eliminated. Repeat with 25 players and 24 objectives, and so on, until only one player remains.",
        color:"Red",
        tags:["lockout", "unplayable", "long"],
        min_teams:26,
        max_teams:26,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Bingo vs. an AI",
        credit: "None",
        description: "Some form of lockout bingo, played against an AI. No such AI currently exists.",
        color:"Red",
        tags:["lockout", "unplayable"],
        min_teams:1,
        max_teams:1,
        min_players_per_team:1,
        max_players_per_team:1
    },
    {
        name: "Gogo",
        credit: "ArrowBounce",
        description: "An identical ruleset to Chessgo, except played on a board of Go.",
        notes: "Use the individual Berry Bingo generator. Playing with cheat mode is recommended. A board size of 9 is recommended for readability. ",
        color:"Orange",
        tags:["lockout", "cursed"],
        min_teams:1,
        max_teams:1,
        min_players_per_team:1,
        max_players_per_team:1
    },
]
